### ISSUE TITLE
Confusion regarding checkpoints

### ISSUE THREAD

**Issue by bfialkoff** [nv-tlabs/datasetGAN_release#1]
Can you please provide greater clarity on where to download the styleGAN checkpoints from?

The linked [repo](https://github.com/NVlabs/stylegan) has pickled models but not checkpoints and certainly not `.pt` checkpoints. Also its a tensorflow implementation so I'm a little confused...

Specfically where can I find:

- `karras2019stylegan-cars-512x384.for_g_all.pt`
- `karras2019stylegan-cats-256x256.for_g_all.pt`
- `karras2019stylegan-celebahq-1024x1024.for_g_all.pt`

**Comment by arieling** [comment]
Thank you for pointing this out. You need to convert the tensorflow checkpoints to pytorch. A good example and script to do such is available at https://github.com/lernapparat/lernapparat/blob/master/style_gan/pytorch_style_gan.ipynb

**Comment by arieling** [comment]
close issue and updated README.

**Comment by ericchansen** [comment]
Wouldn't it be a good idea to add the *.pt checkpoints that have already been converted to the repo or provide them via something like Google Drive?

**Comment by arieling** [comment]
@bfialkoff @ericchansen Thank you for your suggestion. we just released the pytorch checkpoint as you suggested. https://drive.google.com/drive/folders/1Hhu8aGxbnUtK-yHRD9BXZ3gn3bNNmsGi?usp=sharing

**Comment by xunluHu** [comment]
> Thank you for pointing this out. You need to convert the tensorflow checkpoints to pytorch. A good example and script to do such is available at https://github.com/lernapparat/lernapparat/blob/master/style_gan/pytorch_style_gan.ipynb

Sorry,I would like to confirm if this means to use stylegan1 of pytorch version directly to train pretrained model? Thanks.
