### ISSUE TITLE
Question on the StyleGAN version used

### ISSUE THREAD

**Issue by PoissonChasseur** [nv-tlabs/datasetGAN_release#11]
Hello,

In the "README.md" file, the url links which are linked to the StyleGAN point to the Github of the "StyleGAN **V1**", but on the Google Drive, some files seem to be rather linked to the "StyleGAN **V2**" (ex. "Datasetgan_release_checkpoints/styegan_pretrain/**stylegan2**-ffhq-config-f.pt" OR "datasetGAN_data_release/training_latent/car20/latent_**stylegan2**_encoder.npy").

The DatasetGAN can probably work with any version of StyleGAN, but for the research and code of this Github, which version of StyleGAN was used ?

**Comment by arieling** [comment]
ignore the latent_stylegan2_encoder.npy, please use stylegan1 to reproduce results in paper.
