### ISSUE TITLE
stylegan2-ada-pytorch support

### ISSUE THREAD

**Issue by afotonower** [nv-tlabs/datasetGAN_release#13]
Hello, 

Thanks for your great work, I just wanted to know how can we use the stylegan2 pre-trained models for training the interpreter? do you think you will support it in the future?

I have trained my models with stylegan2-ada-pytorch from https://github.com/NVlabs/stylegan2-ada-pytorch

**Comment by arieling** [comment]
hey it will be easy once you gather images features together. we will not update to stylegan-ada in this repo.

**Comment by afotonower** [comment]
> hey it will be easy once you gather images features together. we will not update to stylegan-ada in this repo.

the problem is I can't use tesnorflow, and hence stylegan2-ada-pytorch is the only nvidia repository that I can train my models with. 

there are some scripts for training a stylegan with pytorch (but they're not released by nvidia), do you think your script will support their saved models?

if not, can you also provide a training section for your pytorch stylegan1 script here https://github.com/nv-tlabs/datasetGAN_release/blob/master/models/stylegan1.py

**Comment by arieling** [comment]
I can't see any problem once you can load the pytorch checkpoint and gather feature. Our implementation is based on pytorch.

**Comment by sky-fly97** [comment]
> > hey it will be easy once you gather images features together. we will not update to stylegan-ada in this repo.
> 
> the problem is I can't use tesnorflow, and hence stylegan2-ada-pytorch is the only nvidia repository that I can train my models with.
> 
> there are some scripts for training a stylegan with pytorch (but they're not released by nvidia), do you think your script will support their saved models?
> 
> if not, can you also provide a training section for your pytorch stylegan1 script here https://github.com/nv-tlabs/datasetGAN_release/blob/master/models/stylegan1.py

Hello， have you implemented this part based on stylegan2?

**Comment by arieling** [comment]
Hi yes. you can just replace the stylegan1 code with stylegan2. You can check implementation of [1]. We have tested it internally. It works and has a little bit of improvement on all numbers. 
[1] https://github.com/rosinality/stylegan2-pytorch

**Comment by sky-fly97** [comment]
> Hi yes. you can just replace the stylegan1 code with stylegan2. You can check implementation of [1]. We have tested it internally. It works and has a little bit of improvement on all numbers.
> [1] https://github.com/rosinality/stylegan2-pytorch

Thanks!

**Comment by SarthakJShetty** [comment]
@sky-fly97 apologies for bringing this up, but did you manage to integrate StyleGAN2 with DatasetGAN? If so, how did you deal with `affine_layers`?
