### ISSUE TITLE
How to reduce the number of input features of pixel_classifier

### ISSUE THREAD

**Issue by PoissonChasseur** [nv-tlabs/datasetGAN_release#14]
Hi,

After having trained my own StyleGAN on images of 128x128 pixels in order to then use the DatasetGAN, the code of "train_interpreter.py" indicates that the total number of features that will go into the pixel_classifier (the value dim [-1]) would be of 79,691,776 - which is way too big and just not normal compared to the values presented in the configuration files (.json files).

Is there a way that would allow me to reduce this value or correct this ?

Note: This values of 79,691,776 (= 128x128x4864) was the one giving by the line of code "feature_maps = feature_maps.reshape(-1, args["dim"][2])" in the function "prepare_data"

**Comment by PoissonChasseur** [comment]
OK, trouble solved - just needed to put dim[-1] = 4864 - but it was necessary to go in debug mode to see that information.

**Comment by arieling** [comment]
yes. you can also calculate that by counting stylegan features.

**Comment by ericchansen** [comment]
Can anyone provide more docs on these dimensions and what they should be?
