### ISSUE TITLE
Cat example dies on lines 449 - 450 of train_interpreter.py

### ISSUE THREAD

**Issue by ericchansen** [nv-tlabs/datasetGAN_release#17]
The documentation suggests that we should be able to run `python train_interpreter.py --exp experiments/cat_16.json`. When I do so, the process dies without an error message on lines 449 - 450 (see below).

https://github.com/nv-tlabs/datasetGAN_release/blob/9de77f727d147a4f380469ba098515b999433306/datasetGAN/train_interpreter.py#L449-L450

Can anyone suggest ideas for why this is happening? How about workarounds?

**Comment by arieling** [comment]
Hey it's mainly due to you don't have enough RAM to store all the tenser map. try htop and monitor the RAM usage. 
The way to solve it is to dump the all_feature_maps_train_all to disk and modify dataloader to load from disk accordingly.

**Comment by ericchansen** [comment]
Thanks. I noticed it's working on a machine with ~ 260 GB, but failing on my local machine with 64 GB (due to WSL2, there may only be 32 GB available, not sure). Do you have any examples of the modified dataloader?
