### ISSUE TITLE
RAM required to run images training

### ISSUE THREAD

**Issue by IvanGarcia7** [nv-tlabs/datasetGAN_release#18]
We are planning to adapt the datasetGAN to other contexts, so it is necessary to perform the training phase to obtain the required checkpoint, that is why I would like to know if 160 GB of RAM or VRAM are required to perform the test.

**Comment by PoissonChasseur** [comment]
If you look in detail at the code of the "prepare_data" function in the "train_interpreter.py" file, you will see that the part that requires the most RAM or VRAM is the part related to the "all_feature_maps_train" and "all_mask_train" variables.
- "all_feature_maps_train": Concatenate all the tensors of size [H, W, Channel] linked to the feature maps of each of the images generated by the StyleGAN and which will be used for the training the DatasetGAN.
- "all_mask_train": Concatenate all the tensors of size [H, W] linked to the image mask which will be used for learning the DatasetGAN.

In my case where I trained my own StyleGAN V1 to generate 128x128 pixel colored images, a file linked to a [128, 128, 4864] tensor in float16 uses about 150 MB on the hard drive (and approx 300 MB in float32). So if you have 30 training images that would be around 4.5 GB on disk and we can assume that it would be roughly the same on RAM or VRAM (as a first guess) (only for these 2 variables).

You can use this method to try to estimate how much RAM you would need to be able to use the number of training images you want to use. In my case with 30 training images that are turned into a [128, 128, 4864] tensor, the overall code was using a bit over 16 GB, so a PC with at least 20 GB would be better.

If you do not have enough RAM or VRAM, you can for example save these variables on the disk in several files where each of them gathers a certain number of images. Then, during training, you will simply randomly select the pair of files to load and then randomly select parts of "batch_size" size in each of them (making sure to select the same elements in the 2 variables) .
