### ISSUE TITLE
Cars 32 Class Missing

### ISSUE THREAD

**Issue by mcboyd** [nv-tlabs/datasetGAN_release#20]
Hello. I am interested in getting the full 32 classes for cars as published in the paper. Will you be releasing experiments (JSON files), checkpoints, and other supporting files to allow us to train and generate these 32-class car images and annotations? Thank you for the excellent work so far!

**Comment by arieling** [comment]
sorry I missed this thread.
The car-32 data is also at https://drive.google.com/drive/u/1/folders/17vn2vQOF1PQETb1ZgQZV6PlYCkSzSRSa.

Maybe you checked the wrong link?
