### ISSUE TITLE
Question about key point

### ISSUE THREAD

**Issue by sky-fly97** [nv-tlabs/datasetGAN_release#23]
1. In `class generate_data`， What is the purpose of using 10 models?
2. I noticed `make_ training_ Data.py`  seems to be used to generate data， but I want to train the first stage with my own labeled training data. How should I operate? 

Thank you！

**Comment by arieling** [comment]
1.  We used an ensemble of MLP classifiers to improve performance. 
2. You need to first embed real image in GAN's latent space. An encoder + optimization could work. I encourage you to read [1] for more details. 

[1] Elad Richardson, Yuval Alaluf, Or Patashnik, Yotam Nitzan, Yaniv Azar, Stav Shapiro, and Daniel Cohen-Or. Encoding in style: a stylegan encoder for image-to-image translation. arXiv preprint arXiv:2008.00951, 2020.

**Comment by sky-fly97** [comment]
Hello,I trained 300 epochs with 68 key points of the given 16 face images, but in generate_ Data the results don't look good. Is it because I have too many target key points?
This is generate images 256*256
![image](https://user-images.githubusercontent.com/55578436/132151055-3481b018-114c-472f-be67-13757529d81d.png)
![image](https://user-images.githubusercontent.com/55578436/132155023-3a33d070-8fec-47fd-9df9-e6192448be8a.png)

**Comment by arieling** [comment]
hey. In the paper, we only perform key point detection tasks on car and bird.
Actually applying key point tasks on face is not reasonable. Since stylegan has a pre-processing step which is basically key point detection and affine transformation.  Please refer to https://github.com/NVlabs/ffhq-dataset/blob/master/download_ffhq.py#L339 for more details.

**Comment by sky-fly97** [comment]
> hey. In the paper, we only perform key point detection tasks on car and bird.
> Actually applying key point tasks on face is not reasonable. Since stylegan has a pre-processing step which is basically key point detection and affine transformation. Please refer to https://github.com/NVlabs/ffhq-dataset/blob/master/download_ffhq.py#L339 for more details.

Thanks， 
What appropriate method should I use to modify the code so that it can generate labeled face data? 
Such as retrain a stylegan based on face data?

There is another problem. If I want to generate some large pose tagged face data, how can I adjust the `latent = np.random.randn (1, 512)` in the generated data

**Comment by arieling** [comment]
- You can train a stylegan without pre-processing. 
- Can you explain your the second question in more detail?

**Comment by sky-fly97** [comment]
> * You can train a stylegan without pre-processing.
> * Can you explain your the second question in more detail?

Thank you for your help,
The second problem is that in the first stage, we use the training data for training.
When generating labeled data in the second stage, I want to generate some labeled face images with large facial posture for training my own ldmk detection model.

**Comment by sky-fly97** [comment]
> > * You can train a stylegan without pre-processing.
> > * Can you explain your the second question in more detail?
> 
> Thank you for your help,
> The second problem is that in the first stage, we use the training data for training.
> When generating labeled data in the second stage, I want to generate some labeled face images with large facial posture for training my own ldmk detection model, rather than a fixed frontal pose. So how can I generate such face data?
> ![image](https://user-images.githubusercontent.com/55578436/132820502-ac0b5c02-771e-4c7d-b230-bdcdcf847369.png)
> ![image](https://user-images.githubusercontent.com/55578436/132820533-e560770f-1793-45c1-ac0a-4a8b87023d5b.png)
