### ISSUE TITLE
About the test data in your paper

### ISSUE THREAD

**Issue by AtlantixJJ** [nv-tlabs/datasetGAN_release#24]
In your paper, you have testing datasets selected as a subset from ADE20K and pascal, such as ADE-Car-12 and ADE-car-5. How to obtain these datasets? Because an identical testing dataset is core to a fair comparison. Thank you.

**Comment by arieling** [comment]
Thank you for your interest! We can't release ADE-car testing dataset directly due to the dataset license. 
A benchmark leaderboard will be released soon.
