### ISSUE TITLE
ADE-Car-12 testing set and PASCAL-Car-5 

### ISSUE THREAD

**Issue by yangyu12** [nv-tlabs/datasetGAN_release#25]
Hi,
    Nice work! I am curious about how to construct the ADE-Car-12 and PASCAL-Car-5. In the paper, it says ADE-Car-20 contains 50 and 250 images for training and testing. I wonder what are those exact images (e.g. image index). Are they preprocessed? Is there any instruction for constructing it? I also wonder which 900 images are taken from Pascal Part for PASCAL-Car-5 and how are the 5 classes defined. Thanks very much!

**Comment by arieling** [comment]
Thank you for your interest! We can't release ADE-car testing dataset directly due to the dataset license.
A benchmark leaderboard will be released soon.

**Comment by yangyu12** [comment]
Thanks for your reply! Is it possible to release a description of the image index and the pre-process parameters? For example, a file list as well as a list of boxes if the image is cropped. I am not sure if the intended leaderboard would include such information. Look forward to checking the leaderboard in the future!

**Comment by arieling** [comment]
The cropped images will be released.

**Comment by yangyu12** [comment]
Thanks. I will check it in the future.
