### ISSUE TITLE
Data   and the pre-trained model of bird

### ISSUE THREAD

**Issue by wuzhenyubuaa** [nv-tlabs/datasetGAN_release#28]
Hi, 
can you provide the dataset and the pre-trained of stylegan of bird? Thank you very much!!

**Comment by arieling** [comment]
Hi sorry. the bird data would not be released due to data license constrain.

**Comment by xingzhehe** [comment]
> Hi sorry. the bird data would not be released due to data license constrain.

Could you tell the dataset size of the Bird?
