### ISSUE TITLE
Can I reduce the nums of input features of the final classification layer

### ISSUE THREAD

**Issue by sky-fly97** [nv-tlabs/datasetGAN_release#29]
At present, I use **256 * 256*3 images** for training, and **the final styleGAN output is 256 * 256 * 4864**. Due to the limitation of memory, I can only load the features of about **100** images at a time under **400G memory**, and it will take dozens of minutes. Is there any way to use more images for training? For example, is it feasible to reduce the number of input features？

**Comment by arieling** [comment]
yes you can. you can try to delete the image feature from the first 4 style layers and the final 2 style layers. However, it will be a performance v.s memory trade-off.

**Comment by sky-fly97** [comment]
> yes you can. you can try to delete the image feature from the first 4 style layers and the final 2 style layers. However, it will be a performance v.s memory trade-off.

Thank you very much. I have another question. Because I'm not familiar with the GAN field, I encountered some problems in the replacement process. Can you share the train_interpreter.py of stylegan_v2?  Thank you !

**Comment by sky-fly97** [comment]
> yes you can. you can try to delete the image feature from the first 4 style layers and the final 2 style layers. However, it will be a performance v.s memory trade-off.

By the way, I think you must have done experiments using more labeled data to train? Like 160 instead of 16. What's the effect?

**Comment by arieling** [comment]
Hi. We can't share the internal code of train_interpreter on stylegan_v2 due to license policy. The implementation should be straightforward. 

And yes, we have done such an experiment. It also works with improvement. But we will not share the number at this moment.
