### ISSUE TITLE
Some minor modifications for the "models/stylegan1.py" file and questions about the StyleGAN code 

### ISSUE THREAD

**Issue by PoissonChasseur** [nv-tlabs/datasetGAN_release#3]
Hello,

When I was analyzing all the code in this Github, there are some parts that I had to fix in the "models/stylegan1.py" file:

Class LayerEpilogue:
     -> Change " layers.append(('pixel_norm', PixelNorm())) " to " layers.append(('pixel_norm', PixelNormLayer())) " 

Class G_synthesis:
   ->The Spyder IDE said that the variable "last_channels" was not set because it had not been initialized before the for loop in the "__init__". This is technically not an error here, but I fixed this to remove these error messages.
   -> There are also a few variables that are not used: randomize_noise, num_styles, torgbs, batch_size (in the "foward" method)

Class Downscale2d:
   -> The undefined variable "factor" in the "forward" method is probably "self.factor"

Also, I also did not find any code to be able to train and test the StyleGAN. Are you just using their Github code for this ?
If so, then why define all this code that seems to be related to StyleGAN? (Note that I haven't read the StyleGAN paper or code yet)

**Comment by arieling** [comment]
Thank you for pointing this out. The requirement.txt is updated with right version of pytorch. 
For stylegan, the repo only contains inference code. Please refer to official stylegan paper for details.
