### ISSUE TITLE
AttributeError: module 'scipy.misc' has no attribute 'imsave'

### ISSUE THREAD

**Issue by Schnei1811** [nv-tlabs/datasetGAN_release#32]
Title describes an error I receive with modern scipy. The modern version of scipy doesn't include imsave anymore. Also scipy is not included in the requirements.

**Comment by arieling** [comment]
Thank you for pointing this out. 
This thread should help https://stackoverflow.com/questions/19991665/my-scipy-misc-module-appears-to-be-missing-imsave.
