### ISSUE TITLE
Some questions about the keypoint detection experiments

### ISSUE THREAD

**Issue by ZezhouCheng** [nv-tlabs/datasetGAN_release#33]
Nice work and thanks for sharing the code and data! I have a few questions regarding the keypoint detection experiments in table 2:

1) The exact definition of PCK: I noticed that different papers are using slightly different versions of PCK in terms of the threshold (e.g., the keypoint is considered correct if its distance to GT is within X% of the longer side of an image in some works, while others use the diagonal length of an image as a reference). Could you clarify the PCK metric used in your paper?

2) Is it possible to share the keypoint annotations and images for comparisons?

**Comment by xingzhehe** [comment]
Has you find the answer? I am also interested.
