### ISSUE TITLE
Why you need so much RAM?

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [nv-tlabs/datasetGAN_release#34]
Hey guys,

Amazing work, I was wondering why you need 160GB for 16 images! 

Thanks,

Cheers

**Comment by arieling** [comment]
You don't need to but dumping cache to RAM is the fastest way to load data.  You can cache each image's feature to disk and there will be no difference.

**Comment by Ghy1209** [comment]
Hey guys,, 
I want to know how to cache each image's feature to disk.
Thank you.

**Comment by zhangjingxian1998** [comment]
> Hey guys,, I want to know how to cache each image's feature to disk. Thank you.

maybe torch.save

**Comment by hong-hd** [comment]
> Hey guys,, I want to know how to cache each image's feature to disk. Thank you.

Have you solved it now?
