### ISSUE TITLE
Missing pickle files for training deeplab

### ISSUE THREAD

**Issue by AbdouMechraoui** [nv-tlabs/datasetGAN_release#38]
Hello, 
Thank you so much for providing the code for this paper :)
I am trying to generate an annotated face dataset, but I am having some trouble with the `train_deeplab.py`. 
In ln[95] there is `all_pickle = glob.glob(data_path + '/*.pickle')`, which loads the 16 manually annotated data if I understood the docs correctly. However, I can't seem to find these `.pickle` files. 
I guess one can load the training/test data provided in `dataset_release`, but it would still be missing the `uncertainty_score`.

**Comment by arieling** [comment]
no. The pickle files are created during
Step 2. Run GAN Sampling

**Comment by AbdouMechraoui** [comment]
Thank you so much for your reply :) 
The annotations of face images are lacking color/labels, it is similar to what #36 reported. Does this have anything to do with the color palette chosen? 

Sampled images from Step2:
![label0](https://user-images.githubusercontent.com/52415829/143683108-73f47d94-06b2-4e69-96a1-23d9c719dc21.png)
![img0](https://user-images.githubusercontent.com/52415829/143683109-600a4280-72ae-411a-80c9-2958b94c6cd9.png)

**Comment by arieling** [comment]
https://github.com/nv-tlabs/datasetGAN_release/blob/master/datasetGAN/train_interpreter.py#L318

check this line and function for vis.

**Comment by wenWern** [comment]
> o. The pickle files are created during
> Step 2. Run GAN Sampling

I ran step2. and it creates a folder with images + annonations sampled from the model. I still couldn't get where these pickle files are created.
