### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by ghost** [nv-tlabs/datasetGAN_release#42]
How to run interpreter in Google Colab, I get the error CUDA out of memory

`Opt {'exp_dir': 'model_dir/face_34', 'batch_size': 1, 'category': 'face', 'debug': False, 'dim': [512, 512, 5088], 'deeplab_res': 512, 'number_class': 34, 'testing_data_number_class': 34, 'max_training': 1, 'stylegan_ver': '1', 'annotation_data_from_w': False, 'annotation_mask_path': './dataset_release/annotation/training_data/face_processed', 'testing_path': './dataset_release/annotation/testing_data/face_34_class', 'average_latent': './dataset_release/training_latent/face_34/avg_latent_stylegan1.npy', 'annotation_image_latent_path': './dataset_release/training_latent/face_34/latent_stylegan1.npy', 'stylegan_checkpoint': './checkpoints/stylegan_pretrain/karras2019stylegan-celebahq-1024x1024.for_g_all.pt', 'model_num': 10, 'upsample_mode': 'bilinear'}
MODEL_NUMBER 0
MODEL_NUMBER 1
MODEL_NUMBER 2
MODEL_NUMBER 3
MODEL_NUMBER 4
MODEL_NUMBER 5
MODEL_NUMBER 6
MODEL_NUMBER 7
MODEL_NUMBER 8
MODEL_NUMBER 9
num_sample:  1
Genearte 0 Out of: 1
tcmalloc: large alloc 5335154688 bytes == 0x55a304d12000 @  0x7fc98fd25b6b 0x7fc98fd45379 0x7fc93469bb4a 0x7fc93469d5fa 0x7fc9369cd78a 0x7fc936c1630b 0x7fc936c5db37 0x7fc97fae6325 0x7fc97fae69cb 0x7fc97faea9fe 0x7fc97fac270b 0x55a2ac2f0045 0x55a2ac2b0c52 0x55a2ac3244d9 0x55a2ac31e9ee 0x55a2ac2b1bda 0x55a2ac320737 0x55a2ac31e9ee 0x55a2ac2b1bda 0x55a2ac320737 0x55a2ac31e9ee 0x55a2ac31e6f3 0x55a2ac3e84c2 0x55a2ac3e883d 0x55a2ac3e86e6 0x55a2ac3c0163 0x55a2ac3bfe0c 0x7fc98eb2dbf7 0x55a2ac3bfcea
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "/content/datasetGAN_release/datasetGAN/train_interpreter.py", line 579, in <module>
    generate_data(opts, args.resume, args.num_sample, vis=args.save_vis, start_step=args.start_step)
  File "/content/datasetGAN_release/datasetGAN/train_interpreter.py", line 263, in generate_data
    return_upsampled_layers=True)
  File "../utils/utils.py", line 101, in latent_to_image
    affine_layers[i])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/upsampling.py", line 131, in forward
    return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 2530, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, _output_size(2), align_corners)
RuntimeError: CUDA out of memory. Tried to allocate 8.00 GiB (GPU 0; 15.90 GiB total capacity; 9.27 GiB already allocated; 5.59 GiB free; 9.38 GiB reserved in total by PyTorch)`

**Comment by arieling** [comment]
Our experiments are on Nvidia Tesla V100 GPUs with 32GB memory. You could try to decrease the batch size for 16G memory GPU.

**Comment by getshaun24** [comment]
Hi @DonkeySmall, Did you ever get it working on Colab ?!
