### ISSUE TITLE
My system halted

### ISSUE THREAD

**Issue by whyydsforever** [nv-tlabs/datasetGAN_release#47]
The code seems to take large sum of memory and it makes my computer system halted. So, how large the memory capacity should be?

**Comment by arieling** [comment]
It took 200G RAM. You can change the line of https://github.com/nv-tlabs/datasetGAN_release/blob/master/datasetGAN/train_interpreter.py#L392 to reduce memory.

**Comment by wenWern** [comment]
> It took 200G RAM. You can change the line of https://github.com/nv-tlabs/datasetGAN_release/blob/master/datasetGAN/train_interpreter.py#L392 to reduce memory.
May I know what I should change for this line to reduce memory?

**Comment by lww28** [comment]
> It took 200G RAM. You can change the line of https://github.com/nv-tlabs/datasetGAN_release/blob/master/datasetGAN/train_interpreter.py#L392 to reduce memory.

May I know what I should change for this line to reduce memory?

**Comment by getshaun24** [comment]
> > It took 200G RAM. You can change the line of https://github.com/nv-tlabs/datasetGAN_release/blob/master/datasetGAN/train_interpreter.py#L392 to reduce memory.
> 
> May I know what I should change for this line to reduce memory?

@wenWern, Did you ever figure this out?!
