### ISSUE TITLE
Conflicts between paper and code about DeeplabV3

### ISSUE THREAD

**Issue by greatwallet** [nv-tlabs/datasetGAN_release#7]
Hi. As stated in the original paper, the part segmentation task is trained on Deeplab-V3, with ImageNet pre-trained ResNet151
backbone. However, the code is written as 

https://github.com/nv-tlabs/datasetGAN_release/blob/9de77f727d147a4f380469ba098515b999433306/datasetGAN/train_deeplab.py#L134-L135

Which settings is correct if I want to reproduce your result? BTW, should the argument `pretrained` flag above set to `True` or not, and will it boost the performance？

**Comment by arieling** [comment]
we confirm the setting is under deeplabv3_resnet101 with pretrain flag set to be False.
