### ISSUE TITLE
Lack of definition of 8 classes of CelebAMask-HQ

### ISSUE THREAD

**Issue by greatwallet** [nv-tlabs/datasetGAN_release#9]
Hello.

`CelebAMask-HQ` provides 19 classes of annotation on face according to original paper and their [github repo](https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing).

|  Label list |  |  |
| ----------- | ----------- | ---------- |
0: 'background' | 1: 'skin' | 2: 'nose'
3: 'eye_g' | 4: 'l_eye' | 5: 'r_eye'
6: 'l_brow' | 7: 'r_brow' | 8: 'l_ear'
9: 'r_ear' | 10: 'mouth' | 11: 'u_lip'
12: 'l_lip' | 13: 'hair' | 14: 'hat'
15: 'ear_r' | 16: 'neck_l' | 17: 'neck'
18: 'cloth'| | |

However, in your work only 8 classes are classified. How do you define all those classes?

Moreover, [`SemanticGAN`](https://github.com/nv-tlabs/semanticGAN_code), which is work of your lab as well, seems also adopting 8-classes protocol (See following snapshot from `SemanticGAN`). Do you share the same definition?

![image](https://user-images.githubusercontent.com/30019142/124861143-8bbf3180-dfe5-11eb-8937-4afc9fa20486.png)

BTW, let me make a guess, your mask labels are defined as follow, which could be directly merged by original 19 classes masks.
|  8 classes | ID that corresponds to in original 19 classes  |  
| ----------- | ----------- |
0: 'background' | 0, 3, 14, 15, 16, 17, 18 |
1: 'skin' |  1 | 
2: 'nose' | 2 |
3: 'eye' | 4, 5 | 
4: 'brow' | 6, 7 | 
5: 'ear' | 8, 9 |
6: 'mouth' | 10, 11, 12 |
 7: 'hair' | 13 |

Please reply if I have made it correct. Also, if I am correct about this, how do you deal with `eye_g` (i.e. glasses ) in original settings, since annotating glasses to background will lead to aliases in label image.

Here is a snapshot from original celebAMask-HQ with glasses.
![image](https://user-images.githubusercontent.com/30019142/124861393-11db7800-dfe6-11eb-9a9f-bf2f0b76f438.png)

**Comment by arieling** [comment]
duplicate to https://github.com/nv-tlabs/semanticGAN_code/issues/3
